#!/usr/bin/env bash
# gen-third-party-licenses.sh — generate dist/THIRD_PARTY_LICENSES (and
# stage dist/LICENSE) for release artifacts (#184 / #666).
#
# Concatenates the license text of every Go module the root module (and
# the nested proto module, via the local replace) links against, using
# google/go-licenses. The output ships as a GitHub Release asset and
# inside the .deb (apt users never see the release page), satisfying the
# attribution obligations of the permissive licenses in the dependency
# tree (see docs/reports/20260711-license-selection-investigation.md §6
# in the monorepo).
#
# Usage: bash scripts/ci/gen-third-party-licenses.sh [OUT]
#   OUT: output path (default dist/THIRD_PARTY_LICENSES)
#
# Own modules are excluded — the repo's LICENSE covers them; it is
# copied to dist/LICENSE alongside so packaging picks both from dist/.
set -euo pipefail

OUT="${1:-dist/THIRD_PARTY_LICENSES}"
GO_LICENSES_VERSION="v1.6.0"
MODULE="$(go list -m)"

mkdir -p "$(dirname "${OUT}")"
tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

# `save` copies each dependency's license file into a per-module tree.
# --ignore excludes our own modules (root + nested proto): they are
# first-party, covered by the repo LICENSE, and the local `replace`d
# proto module has no license file of its own.
go run "github.com/google/go-licenses@${GO_LICENSES_VERSION}" save ./... \
  --save_path="${tmp}/licenses" \
  --ignore "${MODULE}" \
  --ignore "${MODULE}/proto"

: > "${OUT}"
printf 'Third-party license notices for %s\n' "${MODULE}" >> "${OUT}"
printf 'Generated by google/go-licenses %s.\n\n' "${GO_LICENSES_VERSION}" >> "${OUT}"
find "${tmp}/licenses" -type f | LC_ALL=C sort | while read -r f; do
  rel="${f#"${tmp}"/licenses/}"
  printf '================================================================\n' >> "${OUT}"
  printf '%s\n' "$(dirname "${rel}")" >> "${OUT}"
  printf '================================================================\n\n' >> "${OUT}"
  cat "${f}" >> "${OUT}"
  printf '\n\n' >> "${OUT}"
done

# Stage the first-party LICENSE next to it so packaging (nfpm contents,
# release-asset lists) can take everything from dist/. In the agent repo
# LICENSE sits at the root; in the monorepo (until the #184 cutover
# deletes the client tree) the same Apache-2.0 text lives only as the
# split template — the packaged client code is licensed identically
# either way, so fall back to it.
if [ -f LICENSE ]; then
  cp LICENSE "$(dirname "${OUT}")/LICENSE"
elif [ -f scripts/dev/split-agent-repo/templates/LICENSE ]; then
  cp scripts/dev/split-agent-repo/templates/LICENSE "$(dirname "${OUT}")/LICENSE"
else
  echo "error: no LICENSE found (repo root or split templates)" >&2
  exit 1
fi

echo "wrote ${OUT} ($(wc -c < "${OUT}") bytes)"
