package gateway

import (
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	dto "github.com/prometheus/client_model/go"

	"github.com/waired-ai/waired-agent/internal/catalog"
	"github.com/waired-ai/waired-agent/internal/observability"
	"github.com/waired-ai/waired-agent/internal/router"
	"github.com/waired-ai/waired-agent/internal/runtime"
)

// TestPhase9Integration_FallbackVisibleOnAllThreeSurfaces is the
// flagship end-to-end test for the Phase 9 plan: a fallback event
// generated by the Phase 8 probe-then-commit pipeline must reach
// every Phase 9 consumer (Prom counter, event ring, state snapshot)
// from a single hot-path request, validating the composite Recorder
// fan-out.
//
// Scenario: peer-A's probe fails (transport_error), peer-C is ready.
// One POST /v1/chat/completions request flows through:
//
//	openai handler → selectAndProbe → ParallelProbe → Commit on peer-C
//	→ setSelectionHeaders → upstream proxy → 200 OK
//
// Assertions:
//
//   - Prom: waired_inference_fallback_total{from_reason="transport_error"} = 1
//   - Ring: an event with kind=fallback and matching from/to fields
//   - State: last_inference.had_fallback = true, peer_id = "peer-C"
//
// The composite Recorder is constructed exactly the way the agent
// does it in cmd/waired-agent/main.go, so this test pins down the
// integration contract between the three sinks and the management
// API endpoints (via direct calls to the handlers package surface).
func TestPhase9Integration_FallbackVisibleOnAllThreeSurfaces(t *testing.T) {
	reg := prometheus.NewRegistry()
	metrics := observability.NewMetrics(reg)
	ring := observability.NewRing(64)
	rec := observability.NewRecorder(ring, metrics, nil)

	rtA := &stubRT{dialErr: errors.New("connect refused")} // probe fails
	rtC := &stubRT{status: 200, body: readyBody(0, 4)}     // probe ready

	upstreamHits := atomic.Int32{}
	upstreamSrv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		upstreamHits.Add(1)
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"choices":[{"message":{"role":"assistant","content":"hi"}}]}`))
	}))
	t.Cleanup(upstreamSrv.Close)

	sel := &phase8MultiSelector{
		cands: []router.Candidate{
			phase8RemoteCandidate("peer-A"),
			phase8RemoteCandidate("peer-C"),
		},
	}
	probeRTs := map[string]http.RoundTripper{"peer-A": rtA, "peer-C": rtC}

	deps := Deps{
		Selector:       sel,
		ListManifests:  func() []catalog.Manifest { return nil },
		AllowOpenAI:    true,
		AllowAnthropic: true,
		HTTPClient:     &http.Client{},
		Recorder:       rec,
		PeerAdapterFactory: func(deviceID string) (runtime.Adapter, error) {
			return phase8FakePeerAdapter{
				transport: splitTransport{probeRT: probeRTs[deviceID]},
				base:      upstreamSrv.URL,
			}, nil
		},
	}
	h := NewHandlerSet(deps)
	gwSrv := httptest.NewServer(h.Handler())
	t.Cleanup(gwSrv.Close)

	// Fire the request.
	body := `{"model":"qwen3-8b-instruct","messages":[{"role":"user","content":"hi"}]}`
	resp, err := http.Post(gwSrv.URL+"/v1/chat/completions", "application/json", strings.NewReader(body))
	if err != nil {
		t.Fatalf("POST: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(resp.Body)
		t.Fatalf("status=%d body=%s", resp.StatusCode, raw)
	}
	if got := resp.Header.Get(HeaderFallbackFrom); got != "peer-A" {
		t.Fatalf("X-Waired-Fallback-From: got %q want peer-A", got)
	}

	// RecordRequest runs in the handler's deferred finish(), which fires
	// after ServeHTTP returns — a scheduling gap that opens after the
	// client has already read the response headers above. Drain the body
	// (so the handler can complete) then wait for the request sink to
	// land before asserting the RecordRequest-derived surfaces (the
	// InferenceRequestsTotal counter, the ring "request" event, and
	// LatestRequest). The fallback/probe counters and the fallback ring
	// event are recorded synchronously during the request, so they need
	// no wait. waitForCounterEq returns on first match, so this adds no
	// latency to the passing path.
	_, _ = io.ReadAll(resp.Body)
	waitForCounterEq(t, 1, metrics.InferenceRequestsTotal, "openai", "success", "")

	// ---- Sink 1: Prom counter ----
	if got := counterVecValue(t, metrics.InferenceFallbackTotal, "transport_error"); got != 1 {
		t.Errorf("Prom counter waired_inference_fallback_total{transport_error}: got %v want 1", got)
	}
	if got := counterVecValue(t, metrics.InferenceRequestsTotal, "openai", "success", ""); got != 1 {
		t.Errorf("Prom counter waired_inference_requests_total{openai,success}: got %v want 1", got)
	}
	if got := counterVecValue(t, metrics.InferenceProbeTotal, "transport_error"); got != 1 {
		t.Errorf("probe_total{transport_error}: got %v want 1 (peer-A failed)", got)
	}
	if got := counterVecValue(t, metrics.InferenceProbeTotal, "ok"); got != 1 {
		t.Errorf("probe_total{ok}: got %v want 1 (peer-C succeeded)", got)
	}

	// ---- Sink 2: event ring ----
	events, _, _ := ring.Since(0, []observability.Kind{observability.KindFallback}, 0)
	if len(events) != 1 {
		t.Fatalf("ring: want 1 fallback event, got %d", len(events))
	}
	if events[0].Fallback.From != "peer-A" || events[0].Fallback.To != "peer-C" {
		t.Errorf("ring fallback event: %+v want From=peer-A To=peer-C", events[0].Fallback)
	}
	if events[0].Fallback.Reason != "transport_error" {
		t.Errorf("ring fallback reason: got %q want transport_error", events[0].Fallback.Reason)
	}

	// Request event should also be in the ring (RecordRequest emit).
	reqs, _, _ := ring.Since(0, []observability.Kind{observability.KindRequest}, 0)
	if len(reqs) != 1 {
		t.Fatalf("ring: want 1 request event, got %d", len(reqs))
	}
	if reqs[0].Request.FallbackFrom != "peer-A" {
		t.Errorf("ring request fallback_from: got %q want peer-A", reqs[0].Request.FallbackFrom)
	}
	if reqs[0].Request.PeerID != "peer-C" {
		t.Errorf("ring request peer_id: got %q want peer-C", reqs[0].Request.PeerID)
	}

	// ---- Sink 3: state derived from ring (LatestRequest path) ----
	latest := ring.LatestRequest()
	if latest == nil || latest.Request == nil {
		t.Fatalf("LatestRequest returned nil after a successful request")
	}
	if latest.Request.PeerID != "peer-C" {
		t.Errorf("LatestRequest peer_id: got %q want peer-C", latest.Request.PeerID)
	}
	if latest.Request.FallbackFrom == "" {
		t.Errorf("LatestRequest should expose fallback_from for state.last_inference.had_fallback")
	}

	// Note: select_decisions_total is emitted by the router's Selector
	// (see router/recorder_test.go), not by the gateway. This test uses
	// a phase8MultiSelector test fake that bypasses the real Selector,
	// so the counter stays at 0 — that's by design, the assertion lives
	// in the router-side integration suite.

	// Upstream proxy must run exactly once (only winner served).
	if upstreamHits.Load() != 1 {
		t.Errorf("upstream hits: got %d want 1", upstreamHits.Load())
	}
}

// TestPhase9Integration_PromHandlerSurfacesAllCollectors asserts the
// /metrics exposition contains every Tier 1 / Tier 2 collector after
// a successful fallback request. This is the test that catches
// silent drops if a future commit removes a MustRegister call.
func TestPhase9Integration_PromHandlerSurfacesAllCollectors(t *testing.T) {
	reg := prometheus.NewRegistry()
	metrics := observability.NewMetrics(reg)
	ring := observability.NewRing(8)
	rec := observability.NewRecorder(ring, metrics, nil)

	// Touch each enum so the vecs surface in the Prom text output.
	rec.RecordRequest(observability.RequestEvent{Kind: "openai", Model: "m", Status: 200})
	rec.RecordFallback(observability.FallbackEvent{From: "a", To: "b", Reason: "capacity_full", Model: "m"})
	rec.RecordProbe("ok", 5)
	rec.RecordSelection("remote", "peer-c", "m")
	rec.RecordBriefQueueRetry("succeeded")
	rec.RecordServed("success", 1500)
	rec.RecordAuthReject("signature")
	rec.SetCapacity(10)
	rec.SetInflight(3)
	rec.SetEngineReady(true, "")
	rec.SetShareEnabled(true, "")
	rec.SetPaused(false, "")
	rec.SetMeshPeers(12, 9, 7)

	srv := httptest.NewServer(promhttp.HandlerFor(reg, promhttp.HandlerOpts{Registry: reg}))
	t.Cleanup(srv.Close)

	resp, err := http.Get(srv.URL)
	if err != nil {
		t.Fatalf("GET /metrics: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	text := string(body)

	want := []string{
		"waired_inference_requests_total",
		"waired_inference_fallback_total",
		"waired_inference_select_decisions_total",
		"waired_inference_probe_total",
		"waired_inference_brief_queue_retry_total",
		"waired_inference_served_total",
		"waired_inference_auth_reject_total",
		"waired_inference_inflight",
		"waired_inference_capacity_total",
		"waired_inference_engine_ready",
		"waired_inference_share_enabled",
		"waired_inference_paused",
		"waired_mesh_peers",
		"waired_inference_probe_latency_milliseconds",
		"waired_inference_request_latency_milliseconds",
		"waired_inference_served_latency_milliseconds",
	}
	for _, name := range want {
		if !strings.Contains(text, name) {
			t.Errorf("/metrics output missing %s", name)
		}
	}
}

// TestPhase9Integration_EventRingCursorRoundTrips drives the
// /observability/events polling protocol the tray will use. After a
// burst of requests the test simulates a tray poll loop: poll with
// since=0, advance the cursor, poll again, advance again — each
// round should return only the new events.
func TestPhase9Integration_EventRingCursorRoundTrips(t *testing.T) {
	ring := observability.NewRing(32)
	rec := observability.NewRecorder(ring, nil, nil)

	// Burst 1: 3 events.
	for i := 0; i < 3; i++ {
		rec.RecordRequest(observability.RequestEvent{Kind: "openai", Model: "m", Status: 200})
	}
	events, _, _ := ring.Since(0, nil, 0)
	if len(events) != 3 {
		t.Fatalf("burst 1: want 3 events, got %d", len(events))
	}
	cursor := events[len(events)-1].Seq

	// Burst 2: 2 events. Polling from cursor should yield only these.
	rec.RecordFallback(observability.FallbackEvent{From: "a", To: "b", Reason: "x", Model: "m"})
	rec.RecordRequest(observability.RequestEvent{Kind: "openai", Model: "m", Status: 200})

	events2, _, gap := ring.Since(cursor, nil, 0)
	if gap {
		t.Errorf("no eviction yet; gap should be false")
	}
	if len(events2) != 2 {
		t.Fatalf("burst 2 since cursor=%d: want 2 events, got %d", cursor, len(events2))
	}
	cursor = events2[len(events2)-1].Seq

	// Burst 3: zero events. Same cursor must return nothing.
	events3, _, _ := ring.Since(cursor, nil, 0)
	if len(events3) != 0 {
		t.Fatalf("idle poll: want 0 events, got %d", len(events3))
	}
}

// TestPhase9Integration_PausedTransitionEmitsEvent confirms the
// polling-driven state-change path: calling SetPaused twice with the
// same value emits nothing, then a transition emits exactly one
// engine_state_change event. This is the contract the agent's
// runObservabilityPoller relies on.
func TestPhase9Integration_PausedTransitionEmitsEvent(t *testing.T) {
	ring := observability.NewRing(16)
	rec := observability.NewRecorder(ring, nil, nil)

	rec.SetPaused(false, "")
	rec.SetPaused(false, "noop")
	if events, _, _ := ring.Since(0, []observability.Kind{observability.KindEngineStateChange}, 0); len(events) != 0 {
		t.Fatalf("same-value SetPaused should not emit; got %d", len(events))
	}

	rec.SetPaused(true, "operator")
	events, _, _ := ring.Since(0, []observability.Kind{observability.KindEngineStateChange}, 0)
	if len(events) != 1 {
		t.Fatalf("transition should emit 1 event; got %d", len(events))
	}
	if events[0].EngineStateChange.To != "paused" {
		t.Errorf("transition to: got %q", events[0].EngineStateChange.To)
	}
	if events[0].EngineStateChange.Reason != "operator" {
		t.Errorf("transition reason: got %q", events[0].EngineStateChange.Reason)
	}
}

// --- local helpers ---

func counterVecValue(t *testing.T, vec *prometheus.CounterVec, labels ...string) float64 {
	t.Helper()
	c, err := vec.GetMetricWithLabelValues(labels...)
	if err != nil {
		t.Fatalf("get counter: %v", err)
	}
	var m dto.Metric
	if err := c.Write(&m); err != nil {
		t.Fatalf("counter write: %v", err)
	}
	return m.GetCounter().GetValue()
}

// waitForCounterEq polls vec{labels} until it equals want, failing the
// test if a 2s deadline passes first. It exists for asynchronously
// recorded sinks (e.g. a handler's deferred RecordRequest): it returns on
// the first matching read, so a sink that is already settled costs ~one
// read and zero added latency on the passing path. GetMetricWithLabelValues
// auto-materialises a zero counter, so a not-yet-incremented sink reads as
// 0 rather than erroring.
func waitForCounterEq(t *testing.T, want float64, vec *prometheus.CounterVec, labels ...string) {
	t.Helper()
	deadline := time.Now().Add(2 * time.Second)
	var got float64
	for {
		if c, err := vec.GetMetricWithLabelValues(labels...); err == nil {
			var m dto.Metric
			if err := c.Write(&m); err == nil {
				got = m.GetCounter().GetValue()
				if got == want {
					return
				}
			}
		}
		if time.Now().After(deadline) {
			t.Fatalf("counter %v: got %v want %v after 2s", labels, got, want)
		}
		time.Sleep(5 * time.Millisecond)
	}
}
