#!/usr/bin/env python3
"""gen-agentgrade-context.py — build the agent-grade probe's session-context
fixture (#322) out of this repository's own source.

The probe's request has to be the weight a coding agent actually sends, and
most of that weight in a real session is accumulated context: project
conventions, files already read, conclusions already drawn. Rather than
inventing 30 KB of plausible-looking code, this assembles it from source we
already own and already publish.

Output: internal/agentgrade/testdata/session-context.md

Run from the repository root, and ONLY when the fixture is deliberately being
re-cut:

    python3 scripts/dev/gen-agentgrade-context.py

The result is checked in and is NOT regenerated by the build. A fixture that
tracked the tree would make two probe runs incomparable, and comparability is
the one property a grading input has to have. Expect the checked-in copy to
drift from the current source; that is fine, it is bulk realistic context and
not documentation. Re-cut it only if the probe's weight needs to change, and
say so in the PR — it invalidates every verdict recorded against the old one.
"""

import io
import os
import sys

OUT = os.path.join("internal", "agentgrade", "testdata", "session-context.md")

# (path, first line, last line). Chosen for density of real types and rules
# rather than for coverage: the point is weight and realism, not a tour.
EXCERPTS = [
    ("internal/router/coding_floor.go", 1, 120),
    ("internal/router/model_picker.go", 90, 260),
    ("internal/router/install_picker.go", 1, 75),
    ("internal/setup/modelselect.go", 100, 205),
    ("proto/catalog/manifest.go", 30, 175),
]

PREAMBLE = """Here is the context for the repository I am working in: the project's \
conventions, and the files I have already read in this session.

# Project conventions

- The wire-protocol module is additive-only once published: exported symbols may
  not be removed, retyped, or renamed, and new fields must serialise away when
  unset. A guard compares every change against the last published tag.
- Tests run with the race detector. A failure that only appears under parallel
  execution is a real defect in the code under test, not a flaky test, and is
  never to be papered over by raising a timeout.
- Errors crossing a package boundary are wrapped with %w so callers can match on
  sentinel values with errors.Is.
- Anything user-facing is written for someone who does not know the internals.
- One decision per file under docs/decisions/, dated. Never a single shared log.

# Files I have read so far

"""

EPILOGUE = """# What I have concluded so far

- The narrowing helper in RankModels discards its filter whenever no candidate
  passes it. That is deliberate for the context floor — a host where nothing
  clears it should still be offered something — but the consequence is that the
  filter does nothing on exactly the hosts where it would matter most.
- RequireCapability has no production caller anywhere in the tree. Every bundled
  manifest advertises the same three capability strings, so wiring it up as-is
  would still be a no-op.
- InstallQualityFloorTier is a coding-QUALITY floor. It says nothing about
  whether a model can drive a tool-calling harness, which is a different axis
  and is currently unmeasured.

# What I still need to work out

- Whether the quality floor and the context floor should compose or whether one
  subsumes the other on small hosts.
- Which of the two failing selection tests encodes the intended behaviour.
"""


def main() -> int:
    if not os.path.isdir(".git"):
        print("run from the repository root", file=sys.stderr)
        return 2

    out = io.StringIO()
    out.write(PREAMBLE)

    missing = []
    for path, start, end in EXCERPTS:
        try:
            with open(path, encoding="utf-8") as f:
                lines = f.read().splitlines()
        except FileNotFoundError:
            missing.append(path)
            continue
        chunk = lines[start - 1 : end]
        if not chunk:
            missing.append(path)
            continue
        out.write(f"## {path} (lines {start}-{start + len(chunk) - 1})\n\n```go\n")
        out.write("\n".join(chunk))
        out.write("\n```\n\n")

    if missing:
        # A silently shrunken fixture is worse than a loud failure: it would
        # quietly lower the weight every future verdict is measured at.
        print(f"ERROR: excerpt sources missing or empty: {', '.join(missing)}", file=sys.stderr)
        print("Update EXCERPTS to point at files that still exist.", file=sys.stderr)
        return 1

    out.write(EPILOGUE)
    body = out.getvalue()

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"wrote {OUT} ({len(body)} bytes)")
    print("NOTE: this invalidates verdicts recorded against the previous fixture.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
