#!/usr/bin/env pwsh
# installtest-pwsh.ps1 -- fast, hermetic, infra-free guard for the install.ps1
# layer. The Windows counterpart of installtest-dash.sh: it drives
# packaging/install/install.ps1 across every CLI/env dispatch path in -DryRun
# and asserts the exit status AND the output, on any host with pwsh.
#
# Why: install.ps1 is 2500 lines with no verification outside the Windows VM
# leg. #177 (an unquoted argv token killed every non-admin install before
# diagnostics were armed) and #192 (WAIRED_* knobs did not survive the UAC
# boundary) both shipped through that gap. The VM leg costs ~5 min per push and
# its runner is already Administrator, so it never crosses Invoke-SelfElevate at
# all -- the exact code path #177 lived in.
#
# Hermetic: install.ps1's un-DryRun-guarded probes of host state are the four
# below, and they are the whole stub surface. Everything privileged goes through
# Common-Run, which is a no-op under -DryRun.
#
#   Test-Admin         WindowsIdentity -- throws outright off Windows; also the
#                      knob that picks elevated-inline vs UAC-handoff
#   Detect-Platform    OSVersion.Version.Build is 0 off Windows, so the real one
#                      dies on the Windows-10-1809 floor
#   Get-Service        the cmdlet does not exist off Windows
#   Start-Process      -Verb RunAs (UAC) and the -Clean wipe child
#   Invoke-RestMethod  api.github.com -- the latest-release lookup
#   Invoke-WebRequest  belt and braces; no case should reach it
#
# They are replaced from OUT HERE, by global aliases, which take precedence over
# a script's own functions. install.ps1 is not modified and carries no test-only
# branch -- the same arrangement as installtest-dash.sh's PATH stubs (CLAUDE.md
# "Test discipline": put the seam below the behaviour under test).
#
# What this does NOT cover, and the Windows leg still owns:
#   * Windows PowerShell 5.1. This runs pwsh 7, deliberately stricter (it also
#     turns Set-StrictMode on, which production does not) -- the dash-vs-sh
#     trade: a stricter interpreter finds latent bugs, and 5.1-only behaviour
#     is what installtest (windows) is for.
#   * Anything past Common-Run: SCM, the registry, WScript.Shell, the real
#     download, a real UAC prompt.
#
# Usage:
#   pwsh -NoProfile -File scripts/dev/installtest-pwsh.ps1
#   $env:INSTALL_PS1 = '/path/to/install.ps1'; pwsh -NoProfile -File ...

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Root = (& git -C $PSScriptRoot rev-parse --show-toplevel).Trim()
$InstallPs1 = if ($env:INSTALL_PS1) { $env:INSTALL_PS1 } else { Join-Path $Root 'packaging/install/install.ps1' }
if (-not (Test-Path -LiteralPath $InstallPs1)) {
    Write-Error "install.ps1 not found: $InstallPs1"
    exit 1
}

# --- host tree ---------------------------------------------------------
# A Windows-shaped filesystem the cases can install into. The directory name
# carries a space on purpose: %ProgramFiles% always has one, and that is the
# token #177 was about.
$Work = Join-Path ([IO.Path]::GetTempPath()) ("waired-installtest-pwsh-" + [Guid]::NewGuid().ToString('N'))
$Host_PF   = Join-Path $Work 'Program Files'
$Host_PD   = Join-Path $Work 'ProgramData'
$Host_TEMP = Join-Path $Work 'Temp Dir'
$Host_WIN  = Join-Path $Work 'Windows'
$Host_USER = Join-Path $Work 'Users/tester'
foreach ($d in @($Host_PF, $Host_PD, $Host_TEMP, (Join-Path $Host_WIN 'System32'), $Host_USER,
                 (Join-Path $Host_USER 'AppData/Roaming'), (Join-Path $Host_USER 'AppData/Local'))) {
    New-Item -ItemType Directory -Path $d -Force | Out-Null
}

# --- the stub preamble each case runs ----------------------------------
# Generated rather than shipped as a second file, so the stubs and the cases
# that depend on them stay in one place (installtest-dash.sh writes its PATH
# stubs the same way).
$Preamble = Join-Path $Work 'stubs.ps1'
Set-Content -LiteralPath $Preamble -Encoding utf8 -Value @'
# Generated by scripts/dev/installtest-pwsh.ps1. Runs install.ps1 with the host
# boundary replaced by global aliases -- which beat a script's own functions,
# so install.ps1 needs no seam of its own.
Set-StrictMode -Version Latest

$global:ItAdmin = [bool]$env:IT_ADMIN

function global:Stub-TestAdmin { $global:ItAdmin }

function global:Stub-DetectPlatform { Write-Host '[itstub] detect-platform' }

# Service presence is a per-case fact since #660: the install-vs-update
# dispatch now asks whether the install is COMPLETE (binary AND registered
# service), so "a binary with no service" and "a real install" are two
# different hosts and the harness has to be able to express both.
#
# Off by default, because Stop-ExistingService / Stop-ServiceForUpdate branch
# on presence and would then reach Stop-Service and sc.exe, which are not
# stubbed. Only cases that return before any service work set it.
function global:Stub-GetService {
    param([string]$Name, $ErrorAction)
    if ($env:IT_SERVICE) { return [pscustomobject]@{ Name = $Name; Status = 'Running' } }
    return $null
}

function global:Stub-StartProcess {
    param([string]$FilePath, [string[]]$ArgumentList, [string]$Verb,
          [switch]$PassThru, [switch]$Wait, [switch]$NoNewWindow, $ErrorAction)
    $tag = if ($Verb) { "elevate verb=$Verb" } else { 'spawn' }
    Write-Host ("[itstub] {0} file={1} argc={2}" -f $tag, $FilePath, $ArgumentList.Count)
    # One line per token, NOT the joined string: whether a space-bearing path
    # survived as one argument is the whole of #177, and joining them back
    # together is exactly the mistake that made it invisible.
    for ($i = 0; $i -lt $ArgumentList.Count; $i++) {
        Write-Host ("[itstub] argv[{0}]={1}" -f $i, $ArgumentList[$i])
    }
    # The -Clean wipe is a real child (`powershell.exe ... -File uninstall.ps1
    # -Clean -Yes [-DryRun]`), so run it in-process, where it inherits these
    # same aliases. installtest-dash.sh asserts the wipe child's own log for the
    # same reason: "install.ps1 printed that it would wipe" is not the contract.
    if (-not $Verb) {
        $f = [Array]::IndexOf($ArgumentList, '-File')
        if ($f -ge 0 -and ($f + 1) -lt $ArgumentList.Count) {
            $child = $ArgumentList[$f + 1].Trim('"')
            # Everything after the script path is a switch in this argv; bind by
            # name so the child gets real parameters rather than positionals.
            $childArgs = @{}
            for ($i = $f + 2; $i -lt $ArgumentList.Count; $i++) {
                $childArgs[$ArgumentList[$i].Trim('"').TrimStart('-')] = $true
            }
            Write-Host ("[itstub] child {0}" -f $child)
            try { & $child @childArgs } catch { Write-Host "[itstub] child-error $_" }
            Write-Host '[itstub] child-exit'
        }
    }
    $rc = 0
    if ($Verb) {
        # Stand in for the artefacts the elevated child leaves behind. The
        # parent's entire diagnosis is now built from these two files (#314),
        # so a stub that skipped them would make every interesting branch
        # unreachable -- which is exactly what the hardcoded ExitCode 0 below
        # used to do to the failure path.
        $s = [Array]::IndexOf($ArgumentList, '-StateFile')
        if ($s -ge 0 -and ($s + 1) -lt $ArgumentList.Count) {
            $statePath = $ArgumentList[$s + 1].Trim('"')
            if ($env:IT_ELEVATE_PROGRESS) {
                Set-Content -LiteralPath "$statePath.progress" -Value ($env:IT_ELEVATE_PROGRESS -split ',')
            }
            if ($env:IT_ELEVATE_STATUS) {
                Set-Content -LiteralPath "$statePath.status" -Value $env:IT_ELEVATE_STATUS
            }
        }
        if ($env:IT_ELEVATE_THROW) {
            # Shape-accurate on purpose. The real cmdlet catches the
            # Win32Exception ShellExecute raised -- 1223 when the user answers
            # No to UAC -- and rethrows a BARE InvalidOperationException with
            # no InnerException, on Windows PowerShell 5.1 and pwsh 7 alike.
            # Reproducing that exactly is the point: install.ps1 code that
            # tries `catch [Win32Exception]` or walks InnerException for
            # NativeErrorCode must fail this case rather than quietly never
            # firing on a real host.
            throw (New-Object System.InvalidOperationException(
                'This command cannot be run due to the error: The operation was canceled by the user.'))
        }
        if ($env:IT_ELEVATE_EXIT) { $rc = [int]$env:IT_ELEVATE_EXIT }
    }
    # install.ps1 no longer passes -Wait for the RunAs arm: it drives the wait
    # itself so it can mirror the child's transcript. So the object has to
    # answer .Handle / .HasExited / .WaitForExit() too, not just .ExitCode.
    $obj = [pscustomobject]@{ ExitCode = $rc; Handle = [IntPtr]::Zero; HasExited = $true }
    $obj | Add-Member -MemberType ScriptMethod -Name WaitForExit -Value { } -PassThru
}

function global:Stub-InvokeRestMethod {
    param([string]$Uri, [switch]$UseBasicParsing, [hashtable]$Headers)
    Write-Host ("[itstub] rest {0}" -f $Uri)
    [pscustomobject]@{ tag_name = $env:IT_LATEST_TAG }
}

function global:Stub-InvokeWebRequest {
    param([string]$Uri, [string]$OutFile, [switch]$UseBasicParsing)
    Write-Host ("[itstub] web {0}" -f $Uri)
    if ($OutFile) { Set-Content -LiteralPath $OutFile -Value '# stub' }
}

Set-Alias -Name Test-Admin         -Value Stub-TestAdmin         -Scope Global
Set-Alias -Name Detect-Platform    -Value Stub-DetectPlatform    -Scope Global
Set-Alias -Name Get-Service        -Value Stub-GetService        -Scope Global
Set-Alias -Name Start-Process      -Value Stub-StartProcess      -Scope Global
Set-Alias -Name Invoke-RestMethod  -Value Stub-InvokeRestMethod  -Scope Global
Set-Alias -Name Invoke-WebRequest  -Value Stub-InvokeWebRequest  -Scope Global

# Parameters arrive as JSON rather than an argv, so a case can express
# `-Control <url>` and `-DryRun` in one table without quoting them twice.
$P = @{}
if ($env:IT_ARGS) {
    foreach ($prop in (ConvertFrom-Json $env:IT_ARGS).PSObject.Properties) {
        $P[$prop.Name] = $prop.Value
    }
}
$global:LASTEXITCODE = 0
& $env:IT_INSTALL_PS1 @P
# install.ps1 fails via Common-Die -> `exit 1`, and `exit` inside a script
# invoked with & ends THAT script only: without this the preamble would go on to
# exit 0 and every "must die" case would pass no matter what.
exit $LASTEXITCODE
'@

# --- host state fixture ------------------------------------------------
# The install.ps1 analog of installtest-dash.sh's dpkg-query stub: an installed
# host is a waired.exe that answers `version --json`. Absent == not installed,
# which is what Get-InstalledVersion actually probes.
$InstallDir = Join-Path $Host_PF 'Waired'
function Set-InstalledVersion {
    param([string]$Version)
    if (-not $Version) {
        if (Test-Path -LiteralPath $InstallDir) { Remove-Item -LiteralPath $InstallDir -Recurse -Force }
        return
    }
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    $exe = Join-Path $InstallDir 'waired.exe'
    Set-Content -LiteralPath $exe -Value @"
#!/bin/sh
case "`$*" in "version --json") printf '{"version":"$Version"}\n' ;; esac
exit 0
"@
    if ($IsLinux -or $IsMacOS) { & chmod +x $exe }
}

# --- runner ------------------------------------------------------------
# The PowerShell analog of the dash harness's FAIL_RE: engine-level failures
# that a case's exit status can hide. install.ps1 traps and re-reports through
# Common-Die, so a binding or platform error can still leave exit 1 looking like
# an ordinary "bad argument" pass.
$FailRe = @(
    'is not recognized as a name of a cmdlet'
    'A positional parameter cannot be found'
    'Cannot bind argument'
    'Cannot bind parameter'
    'PlatformNotSupportedException'
    'MethodInvocationException'
    'Unable to find type'
    'Cannot find drive'
    'cannot be retrieved because it has not been set'   # Set-StrictMode
    'because it is null'
    'You cannot call a method on a null-valued expression'
) -join '|'

$script:Pass = 0
$script:Fail = 0
function Write-Note { param([string]$M) Write-Host "[pwsh-matrix] $M" -ForegroundColor Cyan }
function Write-Ok   { param([string]$M) Write-Host "[pwsh-matrix]  ok  $M" -ForegroundColor Green; $script:Pass++ }
function Write-Bad  { param([string]$M) Write-Host "[pwsh-matrix] FAIL $M" -ForegroundColor Red;   $script:Fail++ }

# Invoke-Case runs install.ps1 once, in a child pwsh: install.ps1 sets script
# state, republishes $env:WAIRED_* for its children and opens transcripts, none
# of which may leak into the next case. -Assert entries are regexes, ALL of
# which must hold; a '!' prefix means "must not match" -- a positive assertion
# alone cannot tell "the branch ran" from "the branch always runs".
function Invoke-Case {
    param(
        [Parameter(Mandatory)][string]$Label,
        [hashtable]$Params = @{},
        [hashtable]$Env = @{},
        [switch]$Admin,
        # The host carries a registered waired-agent service (#660). See
        # Stub-GetService for why this is opt-in per case.
        [switch]$ServiceRegistered,
        [ValidateSet('zero', 'nonzero', 'any')][string]$Expect = 'zero',
        [string[]]$Assert = @()
    )
    $envBlock = @{
        # Windows-shaped environment. install.ps1 resolves %ProgramFiles% /
        # %ProgramData% / %TEMP% / %SystemRoot% at parse time, so these are the
        # floor for it running at all off Windows.
        ProgramFiles           = $Host_PF
        ProgramData            = $Host_PD
        TEMP                   = $Host_TEMP
        TMP                    = $Host_TEMP
        SystemRoot             = $Host_WIN
        USERPROFILE            = $Host_USER
        USERNAME               = 'tester'
        AppData                = (Join-Path $Host_USER 'AppData/Roaming')
        LOCALAPPDATA           = (Join-Path $Host_USER 'AppData/Local')
        PROCESSOR_ARCHITECTURE = 'AMD64'
        IT_INSTALL_PS1         = $InstallPs1
        IT_ARGS                = ($Params | ConvertTo-Json -Compress)
        IT_ADMIN               = $(if ($Admin) { '1' } else { '' })
        IT_SERVICE             = $(if ($ServiceRegistered) { '1' } else { '' })
        IT_LATEST_TAG          = 'v9.9.9'
    }
    foreach ($k in $Env.Keys) { $envBlock[$k] = [string]$Env[$k] }

    # Published on this process and inherited, rather than passed via
    # Start-Process -Environment (PowerShell 7.4+): the harness should run on
    # whatever pwsh a contributor has. Every WAIRED_*/IT_* is cleared first, so
    # a knob one case sets cannot decide the next case's dispatch.
    Get-ChildItem env: |
        Where-Object { $_.Name -like 'WAIRED_*' -or $_.Name -like 'IT_*' } |
        ForEach-Object { Remove-Item -LiteralPath "env:$($_.Name)" -ErrorAction SilentlyContinue }
    foreach ($k in $envBlock.Keys) { Set-Item -LiteralPath "env:$k" -Value ([string]$envBlock[$k]) }

    $outFile = Join-Path $Work 'case.out'
    $argList = @('-NoProfile', '-File', $Preamble)
    $p = Start-Process -FilePath 'pwsh' -ArgumentList $argList -PassThru -Wait -NoNewWindow `
        -RedirectStandardOutput $outFile -RedirectStandardError "$outFile.err"
    $out = ''
    foreach ($f in @($outFile, "$outFile.err")) {
        if (Test-Path -LiteralPath $f) { $out += (Get-Content -LiteralPath $f -Raw -ErrorAction SilentlyContinue) }
    }
    $rc = $p.ExitCode

    if ($out -match $FailRe) {
        Write-Bad "$Label -- PowerShell engine failure:"
        ($out -split "`r?`n" | Select-String -Pattern $FailRe | Select-Object -First 4) |
            ForEach-Object { Write-Host "        $_" }
        return
    }
    if ($Expect -eq 'zero'    -and $rc -ne 0) { Write-Bad "$Label -- expected exit 0, got $rc"; Show-Tail $out; return }
    if ($Expect -eq 'nonzero' -and $rc -eq 0) { Write-Bad "$Label -- expected nonzero, got 0"; Show-Tail $out; return }

    foreach ($want in $Assert) {
        if ($want.StartsWith('!')) {
            if ($out -match $want.Substring(1)) { Write-Bad "$Label -- present: /$($want.Substring(1))/"; Show-Tail $out; return }
        } else {
            if ($out -notmatch $want) { Write-Bad "$Label -- missing: /$want/"; Show-Tail $out; return }
        }
    }
    Write-Ok "$Label (exit $rc)"
}

function Show-Tail {
    param([string]$Text)
    ($Text -split "`r?`n" | Select-Object -Last 15) | ForEach-Object { Write-Host "        $_" }
}

Write-Note "install.ps1 = $InstallPs1"
Write-Note "pwsh        = $($PSVersionTable.PSVersion)"
Write-Note "host tree   = $Work"

try {

# 1. Parse only -- the `sh -n` analog. A syntax error here would make every
#    case below fail identically and uninformatively.
$errors = $null
$null = [System.Management.Automation.Language.Parser]::ParseFile($InstallPs1, [ref]$null, [ref]$errors)
if ($errors -and $errors.Count -gt 0) {
    Write-Bad "parse -- $($errors.Count) error(s): $($errors[0].Message)"
} else {
    Write-Ok 'parse (Parser::ParseFile)'
}

# 2. The stubs are actually in effect. Alias-over-function precedence is
#    documented but non-obvious; if it ever stopped holding, every case would
#    fail on Detect-Platform's Windows-build floor and the cause would not be
#    obvious from the message.
Set-InstalledVersion ''
Invoke-Case -Label 'stub canary (aliases beat script functions)' `
    -Params @{ DryRun = $true; SkipOllama = $true; SkipInit = $true; Yes = $true } -Admin `
    -Assert @('\[itstub\] detect-platform')

# 3. Help.
Invoke-Case -Label '-Help' -Params @{ Help = $true } -Assert @('install\.ps1 -- install Waired for Windows')

# 4. Fresh-install dispatch, elevated inline (Test-Admin true -> Phase 2 runs in
#    process, so the whole privileged step list is exercised in one go).
$fresh = @{ DryRun = $true; SkipOllama = $true; SkipInit = $true; Yes = $true }
Invoke-Case -Label 'fresh (base)' -Params $fresh -Admin `
    -Assert @('Waired is installed', 'dry-run\] Expand-Archive')
Invoke-Case -Label 'fresh -Dev' -Params ($fresh + @{ Dev = $true }) -Admin `
    -Assert @('Control Plane URL: https://app\.dev\.waired\.net')
Invoke-Case -Label 'fresh -Control' -Params ($fresh + @{ Control = 'http://127.0.0.1:9479' }) -Admin `
    -Assert @('Control Plane URL: http://127\.0\.0\.1:9479')
Invoke-Case -Label 'fresh -Edge' -Params ($fresh + @{ Edge = $true }) -Admin `
    -Assert @('latest edge \(main\) build')
Invoke-Case -Label 'fresh -Latest' -Params ($fresh + @{ Latest = $true }) -Admin
Invoke-Case -Label 'fresh -Stable' -Params ($fresh + @{ Stable = $true }) -Admin
Invoke-Case -Label 'fresh WAIRED_VERSION=edge' -Params $fresh -Admin -Env @{ WAIRED_VERSION = 'edge' } `
    -Assert @('latest edge \(main\) build')
Invoke-Case -Label 'fresh -MaskPII' -Params ($fresh + @{ MaskPII = $true }) -Admin
Invoke-Case -Label 'fresh -NonInteractive' -Params ($fresh + @{ NonInteractive = $true }) -Admin
Invoke-Case -Label 'fresh -SkipClaudeProxy' -Params ($fresh + @{ SkipClaudeProxy = $true }) -Admin
Invoke-Case -Label 'fresh WAIRED_NO_TRAY' -Params $fresh -Admin -Env @{ WAIRED_NO_TRAY = '1' } `
    -Assert @('skipping tray binary', '!a "Waired" Start Menu shortcut was created')
# waired-agent#801: the install-time level is a PERSISTED setting, so it must
# reach `waired config log-level` and must NOT reach the argv baked into the
# SCM ImagePath. The negative half is the load-bearing one -- it is the exact
# assert that used to be positive here.
Invoke-Case -Label 'fresh -LogLevel debug' -Params ($fresh + @{ LogLevel = 'debug' }) -Admin `
    -Assert @('config log-level debug', '!-- --log-level', '!--log-level debug')
Invoke-Case -Label 'fresh WAIRED_STATE_DIR' -Params $fresh -Admin -Env @{ WAIRED_STATE_DIR = 'C:\wst' } `
    -Assert @('State / identity:  C:\\wst', '-state-dir=C:\\wst')
# The install.sh spellings, folded in by Normalize-ExtraArgs -- the #746 class:
# PowerShell leaves them unbound, and reading them too late (after -Help, the
# banner, Resolve-ControlUrl or the UAC handoff) is how they went missing.
Invoke-Case -Label 'fresh --dev (install.sh spelling)' `
    -Params @{ DryRun = $true; SkipOllama = $true; SkipInit = $true; Yes = $true; ExtraArgs = @('--dev') } -Admin `
    -Assert @('Control Plane URL: https://app\.dev\.waired\.net')
Invoke-Case -Label 'fresh --control <url> (install.sh spelling)' `
    -Params @{ DryRun = $true; SkipOllama = $true; SkipInit = $true; Yes = $true; ExtraArgs = @('--control', 'http://127.0.0.1:9479') } -Admin `
    -Assert @('Control Plane URL: http://127\.0\.0\.1:9479')
# The init hand-off argv. Go bool flags do not consume the next token, so the
# space form would leave "false" as a positional and `waired init` (cobra.NoArgs)
# would reject it -- both true and false killed enrolment.
Invoke-Case -Label 'init answers reach the argv in = form' `
    -Params @{ DryRun = $true; Control = 'http://127.0.0.1:9479'
             InferenceEnabled = 'false'; ShareWithMesh = 'true' } `
    -Env @{ WAIRED_ARGTEST = '1' } `
    -Assert @('InitArgs=\[.*--inference-enabled=false',
              'InitArgs=\[.*--share-with-mesh=true',
              '!--inference-enabled false', '!--share-with-mesh true')

# 5. Fresh install, NOT elevated -> the UAC handoff. This is the arm the
#    Windows CI leg never reaches, because its runner is already Administrator.
Invoke-Case -Label 'fresh non-admin -> UAC handoff' -Params $fresh `
    -Assert @('Administrator step', '\[itstub\] elevate verb=RunAs file=powershell\.exe',
              'argv\[0\]=-NoProfile', 'argv\[3\]=-File', 'argv\[7\]=-StateFile')

#    ARGTEST reports the predicate that PICKED that arm, so the Windows leg can
#    check it against a real restricted token -- the one thing this harness
#    cannot do, because Test-Admin is stubbed here (#195). Both arms, so a
#    constant-folded Admin= would fail one of them.
Invoke-Case -Label 'ARGTEST Admin=False when not elevated' -Params $fresh `
    -Env @{ WAIRED_ARGTEST = '1' } -Assert @('ARGTEST .*Admin=False')
Invoke-Case -Label 'ARGTEST Admin=True when elevated' -Params $fresh -Admin `
    -Env @{ WAIRED_ARGTEST = '1' } -Assert @('ARGTEST .*Admin=True')

# 6. Value validation happens in Phase 1, before any UAC or download: a typo
#    must not cost a UAC click, nor be reported inside a window that closes.
Invoke-Case -Label 'unknown token dies' -Expect nonzero `
    -Params @{ DryRun = $true; ExtraArgs = @('--bogus') } `
    -Assert @('unknown argument')
# Not "is it a URL": Resolve-ControlUrl is lenient on purpose (a scheme-less
# host is valid, and install.sh validates nothing, so tightening here would be a
# Windows-only divergence). The contract is that a stray FLAG cannot become the
# URL -- waired#746, where `--dev` bound to -Control and enrolment ran against
# `https://--dev`.
Invoke-Case -Label 'stray flag as -Control dies' -Expect nonzero `
    -Params @{ DryRun = $true; Control = '--dev' } `
    -Assert @('looks like a stray flag')
Invoke-Case -Label 'multi-token -Control dies' -Expect nonzero `
    -Params @{ DryRun = $true; Control = 'https://h --dev' } `
    -Assert @('looks like a stray flag')
Invoke-Case -Label 'scheme-less -Control is accepted (parity with install.sh)' `
    -Params ($fresh + @{ Control = 'dev.waired.net' }) -Admin `
    -Assert @('Control Plane URL: dev\.waired\.net')
Invoke-Case -Label 'bad -LogLevel dies' -Expect nonzero `
    -Params @{ DryRun = $true; LogLevel = 'shouty' }
Invoke-Case -Label 'bad -InferenceEnabled dies' -Expect nonzero `
    -Params @{ DryRun = $true; InferenceEnabled = 'maybe' }

# 7. Update dispatch. Get-InstalledVersion and the service fixture drive it.
Set-InstalledVersion '0.0.1'
Invoke-Case -Label 'update -Check (available)' -Params @{ DryRun = $true; Check = $true } `
    -Assert @('Update available: 0\.0\.1 -> 9\.9\.9', '!elevate verb=RunAs')
Invoke-Case -Label 'bare re-run on installed host -> update, declined (no tty)' `
    -Params @{ DryRun = $true; SkipOllama = $true } -ServiceRegistered `
    -Assert @('Re-run with -Update -Yes', 'Update declined\.', '!elevate verb=RunAs')

# (#660) The same host minus the service registration: a binary an aborted
# install or a blocked uninstall left behind. This used to satisfy the
# "installed" test on the strength of its version string alone, so the run was
# dispatched to the update path, declined, and exited 0 -- leaving a machine
# with no service, no state dir and no PATH entry that no number of re-runs
# could repair. It is a broken install to repair, not an install to decline
# updating.
Invoke-Case -Label 'leftover binary, no service -> repair, not "update declined"' `
    -Params @{ DryRun = $true; SkipOllama = $true; Yes = $true; SkipInit = $true } `
    -Assert @('the last install did not finish', '!Update declined\.', '!Re-run with -Update -Yes')

# An explicit -Check / -Update is an operator request and is still honoured on
# a partial install: the dispatch change is only about what a BARE re-run does.
Invoke-Case -Label 'leftover binary, -Check still reports the update' `
    -Params @{ DryRun = $true; Check = $true } `
    -Assert @('Update available: 0\.0\.1 -> 9\.9\.9', '!the last install did not finish')
# 7b. Prerelease ordering (waired-agent#781). Every pair below has the
#     same dotted-numeric part, which the old compare kept and the
#     prerelease it dropped -- so the installer answered "already up to
#     date" to a host eight builds behind, and the campaign had to pin
#     WAIRED_VERSION to reach the build it wanted.
Set-InstalledVersion '0.0.3-rc1'
Invoke-Case -Label 'rc -> next rc is offered' -Params @{ DryRun = $true; Check = $true } `
    -Env @{ IT_LATEST_TAG = 'v0.0.3-rc2' } `
    -Assert @('Update available: 0\.0\.3-rc1 -> 0\.0\.3-rc2')
Invoke-Case -Label 'same rc is up to date' -Params @{ DryRun = $true; Check = $true } `
    -Env @{ IT_LATEST_TAG = 'v0.0.3-rc1' } `
    -Assert @('already up to date', '!Update available')
Invoke-Case -Label 'an earlier rc is not an update' -Params @{ DryRun = $true; Check = $true } `
    -Env @{ IT_LATEST_TAG = 'v0.0.2-rc9' } `
    -Assert @('already up to date', '!Update available')
# rc10 is NEWER than rc2. A lexical compare of the prerelease would call
# this backwards; the digit run is read as a number.
Set-InstalledVersion '0.0.3-rc2'
Invoke-Case -Label 'rc2 -> rc10 is offered' -Params @{ DryRun = $true; Check = $true } `
    -Env @{ IT_LATEST_TAG = 'v0.0.3-rc10' } `
    -Assert @('Update available: 0\.0\.3-rc2 -> 0\.0\.3-rc10')
# The exact pair the campaign was stuck on, in the direction it was stuck.
Set-InstalledVersion '0.0.2-rc8-dev'
Invoke-Case -Label 'rc8-dev -> rc9 is offered' -Params @{ DryRun = $true; Check = $true } `
    -Env @{ IT_LATEST_TAG = 'v0.0.2-rc9' } `
    -Assert @('Update available: 0\.0\.2-rc8-dev -> 0\.0\.2-rc9')
# A prerelease is below the release it leads to, in both directions.
Set-InstalledVersion '0.0.3-rc9'
Invoke-Case -Label 'rc -> its release is offered' -Params @{ DryRun = $true; Check = $true } `
    -Env @{ IT_LATEST_TAG = 'v0.0.3' } `
    -Assert @('Update available: 0\.0\.3-rc9 -> 0\.0\.3')
Set-InstalledVersion '0.0.3'
Invoke-Case -Label 'release is not offered its own rc' -Params @{ DryRun = $true; Check = $true } `
    -Env @{ IT_LATEST_TAG = 'v0.0.3-rc9' } `
    -Assert @('already up to date', '!Update available')

# 7c. A pin has to reach the release URL. install.ps1 used the pin
#     verbatim, so the bare spelling -- the one install.sh documents and
#     accepts -- 404'd on releases/download/0.0.3-rc1 (waired-agent#781).
Set-InstalledVersion '0.0.1'
Invoke-Case -Label 'bare pin resolves to the v-prefixed tag' `
    -Params @{ DryRun = $true; Update = $true; Yes = $true } -Admin `
    -Env @{ WAIRED_VERSION = '0.0.3-rc1' } `
    -Assert @('releases/download/v0\.0\.3-rc1/')
Invoke-Case -Label 'v-prefixed pin resolves to the same tag' `
    -Params @{ DryRun = $true; Update = $true; Yes = $true } -Admin `
    -Env @{ WAIRED_VERSION = 'v0.0.3-rc1' } `
    -Assert @('releases/download/v0\.0\.3-rc1/')

Set-InstalledVersion '0.0.1'
Invoke-Case -Label 'update -Update -Yes -> elevates for the swap' `
    -Params @{ DryRun = $true; Update = $true; Yes = $true } `
    -Assert @('\[itstub\] elevate verb=RunAs', 'argv\[5\]=-StagedZipPath')
Invoke-Case -Label 'update -Update -Yes, already admin -> in-place swap' `
    -Params @{ DryRun = $true; Update = $true; Yes = $true } -Admin `
    -Assert @('Waired updated: 0\.0\.1 ->', '!elevate verb=RunAs')

Set-InstalledVersion '9.9.9'
Invoke-Case -Label 'update -Check (already latest)' -Params @{ DryRun = $true; Check = $true } `
    -Assert @('is already up to date', '!Update available')

# Channel preservation: an edge host that names no channel must stay on edge,
# not silently move onto stable. Mirrors install.sh main().
Set-InstalledVersion '0.0.1~edge.20260610120000+abc1234'
Invoke-Case -Label 'update keeps the edge channel' -Params @{ DryRun = $true; Check = $true } `
    -Assert @('channel=edge')
Invoke-Case -Label 'update -Stable leaves the edge channel' -Params @{ DryRun = $true; Check = $true; Stable = $true } `
    -Assert @('!channel=edge')

Set-InstalledVersion ''
Invoke-Case -Label 'update on a host with nothing installed' -Params @{ DryRun = $true; Update = $true; Yes = $true } `
    -Assert @('installed=not installed')

# 8. Clean install. The wipe is a child process, and "install.ps1 said it would
#    wipe" is not the contract -- the child has to run.
Invoke-Case -Label '-Clean -Yes delegates to uninstall.ps1' `
    -Params @{ DryRun = $true; Clean = $true; Yes = $true; SkipOllama = $true; SkipInit = $true } -Admin `
    -Assert @('\[itstub\] child .*uninstall\.ps1', '\[itstub\] child-exit',
              '!\[itstub\] child-error')
Invoke-Case -Label '-Clean via WAIRED_CLEAN env' `
    -Params @{ DryRun = $true; Yes = $true; SkipOllama = $true; SkipInit = $true } -Admin `
    -Env @{ WAIRED_CLEAN = '1' } `
    -Assert @('\[itstub\] child .*uninstall\.ps1')
Invoke-Case -Label '-Clean + -Check rejected' -Expect nonzero -Params @{ DryRun = $true; Clean = $true; Check = $true } `
    -Assert @('cannot be combined with -Check/-Update')
Invoke-Case -Label '-Clean + -Update rejected' -Expect nonzero -Params @{ DryRun = $true; Clean = $true; Update = $true } `
    -Assert @('cannot be combined with -Check/-Update')

# 9. #177 -- the elevation argv. Start-Process quotes nothing of its own, and
#    both the script path and %TEMP% routinely contain spaces; an unquoted token
#    split into two and the child died on a binding error before its transcript
#    existed, so the UAC window just closed. The stub prints one line per token,
#    so this asserts the tokens did not split, not that a joined string looks
#    right.
#
#    $Host_TEMP is 'Temp Dir' and $Host_PF is 'Program Files', so every path
#    below genuinely carries a space.
Invoke-Case -Label '#177 elevation argv: exactly 9 tokens' -Params $fresh `
    -Assert @('\[itstub\] elevate verb=RunAs file=powershell\.exe argc=9')
Invoke-Case -Label '#177 elevation argv: space-bearing paths stay one quoted token' -Params $fresh `
    -Assert @('argv\[5\]=-StagedZipPath', 'argv\[6\]="[^"]*Temp Dir[^"]*\.zip"',
              'argv\[8\]="[^"]*Temp Dir[^"]*install-state\.json"',
              # a split token would show up as a bare fragment on its own line
              '!(?m)^\[itstub\] argv\[\d+\]=Dir')
Invoke-Case -Label '#177 elevation argv: switches stay unquoted' -Params $fresh `
    -Assert @('(?m)argv\[0\]=-NoProfile$', '(?m)argv\[1\]=-ExecutionPolicy$', '(?m)argv\[2\]=Bypass$')

# 10. #192 -- the knobs that must survive UAC. Start-Process -Verb RunAs rebuilds
#     the environment from scratch, so anything that travelled in $env: was lost
#     in Phase 2. They travel in the state file now; this asserts the round trip
#     through a process whose environment carries none of them.
$stateFile = Join-Path $Work 'state.json'
Invoke-Case -Label '#192 Phase 1 writes the state file' `
    -Params @{ DryRun = $true; InstallDir = 'C:\Program Files\Waired Test'
             Control = 'http://127.0.0.1:9479' } `
    -Env @{ WAIRED_ARGTEST = '1'; WAIRED_ARGTEST_STATEFILE = $stateFile
            WAIRED_NO_TRAY = '1'; WAIRED_STATE_DIR = 'C:\wst' } `
    -Assert @('ARGTEST .*NoTray=True', 'ARGTEST .*StateDir=C:\\wst')
if (Test-Path -LiteralPath $stateFile) {
    Write-Ok '#192 state file exists'
    # Phase 2 with a scrubbed environment: no WAIRED_* at all, only -StateFile.
    # This is the only way to observe the boundary without real elevation.
    Invoke-Case -Label '#192 Phase 2 recovers the knobs from -StateFile alone' -Admin `
        -Params @{ StagedZipPath = $stateFile; StateFile = $stateFile } `
        -Env @{ WAIRED_ARGTEST = '1' } `
        -Assert @('ARGTEST .*NoTray=True', 'ARGTEST .*StateDir=C:\\wst',
                  'ARGTEST .*InstallDir=C:\\Program Files\\Waired Test',
                  'ARGTEST .*ControlUrl=http://127\.0\.0\.1:9479')
} else {
    Write-Bad '#192 state file was not written'
}

# 11. #314 -- what the parent says when the elevated phase does not exit 0.
#     None of this was reachable before: the Windows CI leg runs elevated and
#     so never enters Invoke-SelfElevate at all, and this stub hardcoded
#     ExitCode 0. Every assert below is a product contract, not a snapshot.
#
#     The pre-elevation notice: the reviewed operators closed the elevated
#     window partly because nothing said it was the one doing the work.
Invoke-Case -Label '#314 parent says where the work happens before UAC' -Params $fresh `
    -Assert @('The rest of setup runs THERE', 'Do NOT close that window')

#     STATUS_CONTROL_C_EXIT is what Windows reports for a closed console. The
#     bare signed integer is what users saw and could not act on; the negative
#     assert keeps it from regressing to that.
Invoke-Case -Label '#314 closed window decodes instead of a bare NTSTATUS' -Params $fresh -Expect nonzero `
    -Env @{ IT_ELEVATE_EXIT = '-1073741510' } `
    -Assert @('Administrator window was closed', '0xC000013A',
              'setup did not finish', '!(?m)exited code -1073741510\s*\.')

#     The highest-value case in the file: a run that COMPLETED and whose
#     window was closed at the "Press Enter" pause exits the same way as one
#     killed mid-setup. Before the done sentinel the parent called Common-Die
#     on a fully successful install.
Invoke-Case -Label '#314 done sentinel turns a closed success window into exit 0' -Params $fresh `
    -Env @{ IT_ELEVATE_EXIT = '-1073741510'; IT_ELEVATE_PROGRESS = 'files-ok,service-running,init-ok,done' } `
    -Assert @('setup had already finished', '!setup did not finish')

#     A cause the child managed to record still wins over the decode: the
#     marker is specific, the exit code is generic.
Invoke-Case -Label '#314 .status marker still wins over the exit-code decode' -Params $fresh -Expect nonzero `
    -Env @{ IT_ELEVATE_EXIT = '1'; IT_ELEVATE_STATUS = 'disk was full' } `
    -Assert @('disk was full', '!Administrator window was closed')

#     Breadcrumbs drive the recap, so a half-done run reports what survived
#     rather than a blanket failure.
Invoke-Case -Label '#314 recap reports how far setup actually got' -Params $fresh -Expect nonzero `
    -Env @{ IT_ELEVATE_EXIT = '-1073741510'; IT_ELEVATE_PROGRESS = 'files-ok,service-installed' } `
    -Assert @('It stopped during: starting the background service',
              'What is on this machine now', 'Sign in:\s+not reached')
Invoke-Case -Label '#314 recap distinguishes a failed sign-in from an unreached one' -Params $fresh -Expect nonzero `
    -Env @{ IT_ELEVATE_EXIT = '-1073741510'; IT_ELEVATE_PROGRESS = 'files-ok,service-running,path-ok,init-start,init-failed' } `
    -Assert @('Sign in:\s+did not complete')

#     #310 -- and a sign-in that COMPLETED on a device with no local inference is a
#     third answer again. `waired init` exits 3 for it, so calling it "did not
#     complete" would send the operator to re-run a sign-in that already
#     worked, while calling it "completed" would hide the only thing that did
#     go wrong.
Invoke-Case -Label '#310 recap separates a completed sign-in with no local inference' -Params $fresh -Expect nonzero `
    -Env @{ IT_ELEVATE_EXIT = '-1073741510'; IT_ELEVATE_PROGRESS = 'files-ok,service-running,path-ok,init-start,init-no-ai' } `
    -Assert @('Sign in:\s+completed, but local inference is not running', '!did not complete')

#     A declined UAC prompt never returns a process at all -- Start-Process
#     raises a terminating error. It used to reach the trap and print only the
#     localized OS string.
Invoke-Case -Label '#314 declined elevation explains itself' -Params $fresh -Expect nonzero `
    -Env @{ IT_ELEVATE_THROW = '1' } `
    -Assert @('The Administrator step did not start', 'choosing No on the Administrator \(UAC\) prompt',
              'Windows reported: This command cannot be run')

# 12. #314 -- per-run transcript names. A fixed name plus -Force meant the next
#     run destroyed the failed run's evidence, which is how one reviewed host
#     lost its only useful log.
Invoke-Case -Label '#314 install log is per-run, not a fixed name' -Params $fresh `
    -Assert @('waired-install-\d{8}-\d{6}-\d+\.log', '!waired-install\.log')

# 13. #819 -- Extract-Zip must never leave the install directory unusable.
#     Delegated to installtest-swap.ps1, which installtest-windows.ps1 also
#     runs: the case that reproduces #819 needs a held-open file, and Unix
#     has no mandatory locking, so this OS can only assert the part it can
#     actually demonstrate. Same script, two runners, one implementation.
& (Join-Path $PSScriptRoot 'installtest-swap.ps1') -InstallPs1 $InstallPs1
if ($LASTEXITCODE -ne 0) { Write-Bad 'installtest-swap.ps1 reported failures' }
else { Write-Ok 'installtest-swap.ps1 (Extract-Zip stages, then replaces per file)' }

} finally {
    Remove-Item -LiteralPath $Work -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host ''
Write-Note "summary: $script:Pass passed, $script:Fail failed"
if ($script:Fail -gt 0) { exit 1 }
